FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y build-essential wget zlib1g-dev

WORKDIR /usr/local/src
RUN wget https://www.openssl.org/source/openssl-3.0.3.tar.gz
RUN tar -xf openssl-3.0.3.tar.gz
WORKDIR /usr/local/src/openssl-3.0.3

RUN ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
RUN make
RUN make install

ENV PATH="${PATH}:/usr/local/ssl/bin"

WORKDIR /

RUN apt-get install -y openjdk-17-jdk

ARG CRYPTO=certificates

COPY ${CRYPTO}/certificate.crt /${CRYPTO}/certificate.crt
COPY ${CRYPTO}/privateKey.key /${CRYPTO}/privateKey.key

ARG DEPENDENCY=build/dependency
# first layer with the external libs (i.e. the files that change the least).
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
# second layer with the 'META-INF' contents.
COPY ${DEPENDENCY}/META-INF /app/META-INF
# last layer with the application JARs (i.e. the files that change the most).
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","pt.isel.ps.anonichat.AnonichatApplicationKt"]